# Minecraft 1.21.1 - very widely used, big modpack version. Fabric + NeoForge.
minecraft_version=1.21.1
java_version=21
loom_version=1.7.4
fabric_loader_version=0.19.5
fabric_api_version=0.116.17+1.21.1
neoforge_version=21.1.+
forge_version=
